name: ESP Build

on:
  push:

jobs:
  test_builds:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test-platform:
          - nodemcuv2
          - esp32

    outputs:
      lfs-esp8266: ${{ steps.getlfssize.outputs.lfs_nodemcuv2 }}
      lfs-esp32: ${{ steps.getlfssize.outputs.lfs_esp32 }}

    steps:
      - name: Select Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install PlatformIO
        run: |
          pip install -U https://github.com/platformio/platformio-core/archive/master.zip
          platformio update

      - name: Check out the Release
        uses: actions/checkout@v2

      - name: Build FS for ${{ matrix.test-platform }}
        run: platformio run -e ${{ matrix.test-platform }} -t buildfs

      - name: Mount drive & get actual size
        id: getlfssize
        run: |
          chmod +x lfs tools/mklittlefs
          export LOOP=/dev/loop6
          sudo chmod a+rw ${LOOP}
          losetup ${LOOP} .pio/build/${{matrix.test-platform}}/littlefs.bin
          mkdir -p mount
          ./lfs --block_size=8192 ${LOOP} mount
          export USED_SPACE=$(df -h mount | grep -v "Used" | awk '{print $3}')
          echo "::set-output name=lfs_${{ matrix.board }}::${USED_SPACE}"
