name: ESP Build

on:
  push:

jobs:
  test_builds:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test-platform:
          - nodemcuv2
#          - esp32

    steps:
#       - name: Check out the Release
#         uses: actions/checkout@v2

       - name: install fuse-dev
         run:
          fusermount -V
           ls -la /dev/loop*
           sudo apt-get install libfuse-dev

       - name: Check out lfs
         uses: actions/checkout@v2
         with:
          repository: littlefs-project/littlefs-fuse
          path: lfs

       - name: Compile lfs
         run: |
           cd lfs
           make
           ./lfs --help

#      - name: Select Python 3.7
#        uses: actions/setup-python@v1
#        with:
#          python-version: '3.7'
#          architecture: 'x64'
#
#      - name: Install PlatformIO
#        run: |
#          pip install -U https://github.com/platformio/platformio-core/archive/master.zip
#          platformio update
#
#      - name: Check out the Release
#        uses: actions/checkout@v2
#
#      - name: Build FS for ${{ matrix.test-platform }}
#        run: platformio run -e ${{ matrix.test-platform }} -t buildfs