name: ESP Build

on:
  push:

jobs:
  test_builds:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        board:
#          - nodemcuv2
          - esp32

    outputs:
      lfs-esp8266: ${{ steps.get_lfs_size.outputs.lfs_nodemcuv2 }}
      lfs-esp32: ${{ steps.get_lfs_size.outputs.lfs_esp32 }}

    steps:
      - name: Cache pip
        uses: actions/cache@v2
        with:
         path: ~/.cache/pip
         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
         restore-keys: ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Check out the Release
        uses: actions/checkout@v2

      - name: Change permissions for exec files
        run: chmod +x tools/*

      - name: Build FS for ${{ matrix.board }}
        run: platformio run -e ${{ matrix.board }} -t buildfs

      #TODO(DIMI): need to merge this 2 workflows in one
      #ESP8266: "mklittlefs" -c resources -p 256 -b 8192 -s 1024000 .pio/build/nodemcuv2/littlefs.bin
      #ESP32: "tools/mklittlefs" -c resources -p 256 -b 4096 -s 1507328 .pio/build/esp32/spiffs.bin
      - name: Mount drive & get actual size
        id: get_lfs_size
        run: |
          export BLOCK_SIZE=8192
          if [ "${{ matrix.board }}" == "esp32" ]; then
            export BLOCK_SIZE=4096
          fi
          echo ${BLOCK_SIZE}

          export LOOP=/dev/loop6
          sudo chmod a+rw ${LOOP}
          losetup ${LOOP} .pio/build/${{matrix.board}}/**.bin
          mkdir -p mount
          ./tools/lfs --block_size=${BLOCK_SIZE} ${LOOP} mount
          export USED_SPACE=$(df -h mount | grep -v "Used" | awk '{print $3}')
          echo "::set-output name=lfs_${{ matrix.board }}::${USED_SPACE}"
