name: ESP Build

on:
  - pull_request

jobs:
  size_master:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        board:
          - nodemcuv2
#          - esp32

    outputs:
      ram-esp8266: ${{ steps.memsizecalc.outputs.ram_nodemcuv2 }}
      ram-esp32: ${{ steps.memsizecalc.outputs.ram_esp32 }}
      flash-esp8266: ${{ steps.memsizecalc.outputs.flash_nodemcuv2 }}
      flash-esp32: ${{ steps.memsizecalc.outputs.flash_esp32 }}

    steps:
      - name: Check out master
        uses: actions/checkout@v2
        with:
         repository: 'shafr/esp-canary'
         ref: 'master'

      - name: Calculate Used Mem Size
        id: memsizecalc
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "::set-output name=ram_${{ matrix.board }}::${{ matrix.board-ram }}"
          echo "::set-output name=flash_${{ matrix.board }}::${{ matrix.board-flash }}"

  publish_size:
    runs-on: ubuntu-latest
    needs: 
      - size_master
    steps:
      - name: publish size with pull request
        if: ${{ github.event_name == 'pull_request' }}
        uses: jdvr/action-add-comment@main
        with:
          comment: "[CURRENT][$BOARD][RAM $RAM_NEW] [FLASH $FLASH_NEW]"
        env:
          GITHUB_TOKEN: ${{github.token}}
          RAM_NEW: "${{needs.size_master.outputs.ram-esp8266}}"
          FLASH_NEW: "${{needs.size_master.outputs.flash-esp8266}}"
          BOARD: "esp-8266"
