name: ESP Build

on:
  pull_request:

jobs:
  cpplint:
    name: runner / cpplint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code.
      uses: actions/checkout@v2
      
    - name: Setup cppcheck
      run: sudo apt-get install -y cppcheck
        
    - name: Setup reviewdog
      run: |
        mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin        
        
    - name: cpplint
      uses: reviewdog/action-cpplint@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-check
        flags: --linelength=120
        filter: -whitespace/tab    
        
    - name: list files
      run: ls -la
      
    - name: cppcheck
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ runner.workspace }}
        cppcheck --version
        $HOME/bin/reviewdog -reporter=github-pr-check -runners=cppcheck -f 'cppcheck'        
        
# --enable=all --template="{file}:{line}:{message}" src/        
        
