name: Size Fetching

on:
  push:

jobs:
  test_builds:

    runs-on: ubuntu-latest

    steps:
      - name: Select Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install PlatformIO
        run: |
          pip install -U https://github.com/platformio/platformio-core/archive/master.zip
          platformio update
          
      - name: Check out the Release
        uses: actions/checkout@v2

      - name: Run PlatformIO for nodemcuv2
        run: |
          platformio run -e nodemcuv2 | tee log.txt
          RAM_SIZE=$(cat log.txt| grep RAM: | awk '{print $4}')
          echo "RAM_SIZE=${RAM_SIZE}" >> $GITHUB_ENV

      - name: Set ram size
        run: echo "${{ env.RAM_SIZE }}"

