name: Size Fetching

on:
  push:

jobs:
  test_builds:

    runs-on: ubuntu-latest

    steps:
      - name: Select Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install PlatformIO
        run: |
          pip install -U https://github.com/platformio/platformio-core/archive/master.zip
          platformio update
          
      - name: Check out the Release
        uses: actions/checkout@v2

      - name: Run PlatformIO for nodemcuv2
        run: |
          platformio run -e nodemcuv2 | tee log.txt
          echo "RAM_SIZE=$(cat log.txt| grep 'RAM:' | awk '{print $4}')" >> $GITHUB_ENV
          echo "FLASH_SIZE=$(cat log.txt| grep 'Flash:' | awk '{print $4}')" >> $GITHUB_ENV

      - name: Print Ram Size
        run: echo "${{ env.RAM_SIZE }}"

      - name: Print Flash Size
        run: echo "${{ env.FLASH_SIZE }}"

      - uses: jdvr/action-add-comment@main
        with:
          comment: "RAM 📝: ${RAM} | FLASH :clamp::floppy_disk: : ${FLASH}"
        env:
          BUILD_NUMBER: 1234
          RAM: ${{ env.RAM_SIZE }}
          FLASH: ${{ env.FLASH_SIZE }}"